[theme]
primaryColor = "#0c1d36"
backgroundColor = "#ececec"
secondaryBackgroundColor = "#ffffff"
textColor = "#1a2b3c"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
